/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/config-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Check
         * @description Check that the deck, data directory and dictionary are usable.
         */
        get: operations["getConfigCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Build
         * @description The most recent build.
         *
         *     Raises:
         *         HTTPException: 404 when no build has run yet.
         */
        get: operations["getLatestContentBuild"];
        put?: never;
        /**
         * Start Build
         * @description Start a content build in the background.
         *
         *     Raises:
         *         HTTPException: 409 when another build is already running.
         */
        post: operations["startContentBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/build/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Build
         * @description A build by id (only recent builds are remembered).
         *
         *     Raises:
         *         HTTPException: 404 when the build is unknown.
         */
        get: operations["getContentBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange the configured username and password for tokens.
         *
         *     Raises:
         *         HTTPException: 429 while the client address is throttled, 401 for bad credentials.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a refresh token for a new token pair.
         *
         *     Raises:
         *         HTTPException: 401 when the token is invalid, expired or not a refresh token.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Content Summary
         * @description Counts and build metadata for ``content.db``; ``built: false`` if absent or unreadable.
         */
        get: operations["getContentSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report the health of the service's dependencies (503 when one is in error).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Review
         * @description Grade a card. Returns the counts of what is left.
         *
         *     Raises:
         *         UnknownItemError: Mapped to 404 by the app.
         *         StaleReviewError: Mapped to 409 by the app.
         *         ContentNotReadyError: Mapped to 503 by the app.
         */
        post: operations["answerReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Next Review
         * @description The next card to study, or none (with the time the next one comes due).
         *
         *     Fetching a card creates nothing: an unanswered new card is offered again next time.
         *
         *     Raises:
         *         ContentNotReadyError: Mapped to 503 by the app.
         */
        get: operations["getNextReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description The current review settings (defaults until they are first saved).
         */
        get: operations["getSettings"];
        /**
         * Update Settings
         * @description Replace the review settings. All fields are validated together; nothing is saved on error.
         *
         *     Omitted fields take their defaults (this is a full replacement, not a patch).
         */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats Summary
         * @description Today's work, 30 days of history, retention and progress per type and level.
         */
        get: operations["getStatsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerRequest
         * @description Body of ``POST /reviews/answer``.
         */
        AnswerRequest: {
            direction: components["schemas"]["CardDirection"];
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Expected Last Review
             * @description The card's `expected_last_review` from `GET /reviews/next`, unchanged (null for a new card). An opaque token: send it back exactly as received, byte for byte, and never parse or reformat it. A mismatch means the card changed since it was fetched: 409.
             */
            expected_last_review: string | null;
            grade: components["schemas"]["Grade"];
            /** Item Id */
            item_id: string;
        };
        /**
         * BuildEventModel
         * @description A build event as sent over the WebSocket.
         */
        BuildEventModel: {
            /** Error */
            error: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "progress" | "state";
            progress: components["schemas"]["BuildProgressModel"] | null;
            state: components["schemas"]["BuildState"];
            /** Task Id */
            task_id: string;
        };
        /**
         * BuildProgressModel
         * @description Progress of a running build.
         */
        BuildProgressModel: {
            /** Current */
            current: number;
            /** Stage */
            stage: string;
            /** Total */
            total: number;
        };
        /**
         * BuildReportModel
         * @description Summary of a finished build.
         */
        BuildReportModel: {
            /** Deck Sha256 */
            deck_sha256: string;
            /** Dry Run */
            dry_run: boolean;
            /** Duration Seconds */
            duration_seconds: number;
            /** Kana Count */
            kana_count: number;
            /** Kanji By Level */
            kanji_by_level: {
                [key: string]: number;
            };
            /** Kanji Count */
            kanji_count: number;
            /** Kanji Without Details */
            kanji_without_details: number;
            /** Sentence Count */
            sentence_count: number;
            /** Target */
            target: string;
            /** Unleveled Kanji Count */
            unleveled_kanji_count: number;
            /** Vocab By Level */
            vocab_by_level: {
                [key: string]: number;
            };
            /** Vocab Count */
            vocab_count: number;
        };
        /**
         * BuildRequest
         * @description Body of ``POST /admin/content/build``.
         */
        BuildRequest: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /**
         * BuildState
         * @description Lifecycle of a build task.
         * @enum {string}
         */
        BuildState: "running" | "succeeded" | "failed";
        /**
         * BuildStatusResponse
         * @description State of a build task.
         */
        BuildStatusResponse: {
            /** Dry Run */
            dry_run: boolean;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            progress: components["schemas"]["BuildProgressModel"] | null;
            report: components["schemas"]["BuildReportModel"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["BuildState"];
            /** Task Id */
            task_id: string;
        };
        /**
         * CardDirection
         * @description Which way a card asks its question. Each direction belongs to one item type.
         * @enum {string}
         */
        CardDirection: "glyph_to_sound" | "sound_to_glyph" | "kanji_to_meaning" | "kanji_to_reading" | "meaning_to_kanji" | "recognition" | "recall";
        /**
         * CardView
         * @description A card ready to show: identity, scheduling facts and the content item.
         *
         *     Exactly one of ``kana``, ``kanji`` and ``vocab`` is set, matching ``item_type``. Send
         *     ``expected_last_review`` back exactly as received when answering.
         */
        CardView: {
            direction: components["schemas"]["CardDirection"];
            /**
             * Expected Last Review
             * @description An opaque token (null for a new card): send it back exactly as received, byte for byte, in `POST /reviews/answer`. Never parse or reformat it; a client that re-serialises the timestamp can lose microseconds and get a permanent 409.
             */
            expected_last_review: string | null;
            intervals: components["schemas"]["GradeIntervals"];
            /** Is New */
            is_new: boolean;
            /** Item Id */
            item_id: string;
            item_type: components["schemas"]["ItemType"];
            kana?: components["schemas"]["Kana"] | null;
            kanji?: components["schemas"]["Kanji"] | null;
            state: components["schemas"]["SchedState"];
            vocab?: components["schemas"]["Vocab"] | null;
        };
        /**
         * CheckResultModel
         * @description One config check.
         */
        CheckResultModel: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * ComponentHealthModel
         * @description Health of one component.
         */
        ComponentHealthModel: {
            /** Detail */
            detail: string;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
        };
        /**
         * ConfigCheckResponse
         * @description Response of ``GET /admin/config-check``.
         */
        ConfigCheckResponse: {
            /** Checks */
            checks: components["schemas"]["CheckResultModel"][];
            /** Ok */
            ok: boolean;
        };
        /**
         * ContentSummaryResponse
         * @description Response of ``GET /content/summary``.
         *
         *     ``kanji`` counts every kanji row; ``unleveled_kanji`` of them have no JLPT level and are
         *     not offered as lessons.
         */
        ContentSummaryResponse: {
            /** Built */
            built: boolean;
            /**
             * Kana
             * @default 0
             */
            kana: number;
            /**
             * Kanji
             * @default 0
             */
            kanji: number;
            /** Kanji By Level */
            kanji_by_level: {
                [key: string]: number;
            };
            /** Meta */
            meta: {
                [key: string]: string;
            };
            /**
             * Unleveled Kanji
             * @default 0
             */
            unleveled_kanji: number;
            /**
             * Vocab
             * @default 0
             */
            vocab: number;
            /** Vocab By Level */
            vocab_by_level: {
                [key: string]: number;
            };
        };
        /**
         * DayCount
         * @description Reviews on one study day.
         */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Reviews */
            reviews: number;
        };
        /**
         * ErrorResponse
         * @description Body of every error response except 422: a human-readable message.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * Grade
         * @description How well the card was recalled.
         * @enum {integer}
         */
        Grade: 1 | 2 | 3 | 4;
        /**
         * GradeIntervals
         * @description Seconds until the card would be due again, for each grade (for button labels).
         */
        GradeIntervals: {
            /** Again */
            again: number;
            /** Easy */
            easy: number;
            /** Good */
            good: number;
            /** Hard */
            hard: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response of ``GET /health``.
         */
        HealthResponse: {
            /** Components */
            components: {
                [key: string]: components["schemas"]["ComponentHealthModel"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /** Version */
            version: string;
        };
        /**
         * ItemType
         * @description The kind of content a card is about.
         * @enum {string}
         */
        ItemType: "kana" | "kanji" | "vocab";
        /**
         * JlptLevel
         * @description JLPT level. As on the exam, a higher number is easier (N5 is the easiest).
         * @enum {integer}
         */
        JlptLevel: 1 | 2 | 3 | 4 | 5;
        /**
         * Kana
         * @description A single kana character (or yōon combination).
         */
        Kana: {
            /** Char */
            char: string;
            /** Group */
            group: string;
            /** Id */
            id: string;
            kind: components["schemas"]["KanaKind"];
            /** Romaji */
            romaji: string;
            script: components["schemas"]["KanaScript"];
        };
        /**
         * KanaKind
         * @description Kana category.
         * @enum {string}
         */
        KanaKind: "basic" | "dakuten" | "youon";
        /**
         * KanaScript
         * @description Kana writing system.
         * @enum {string}
         */
        KanaScript: "hira" | "kata";
        /**
         * Kanji
         * @description A kanji with its derived JLPT level (``None`` when the deck does not use it).
         */
        Kanji: {
            /** Char */
            char: string;
            /** Frequency */
            frequency?: number | null;
            /** Grade */
            grade?: number | null;
            /** Id */
            id: string;
            /**
             * Kun Readings
             * @default []
             */
            kun_readings: string[];
            level: components["schemas"]["JlptLevel"] | null;
            /**
             * Meanings
             * @default []
             */
            meanings: string[];
            /**
             * On Readings
             * @default []
             */
            on_readings: string[];
            /** Radical */
            radical?: number | null;
            /** Stroke Count */
            stroke_count?: number | null;
        };
        /**
         * LevelProgress
         * @description Progress through one JLPT level of one item type.
         */
        LevelProgress: {
            /** Introduced */
            introduced: number;
            item_type: components["schemas"]["ItemType"];
            /** Level */
            level: string;
            /** Review */
            review: number;
            /** Total */
            total: number;
        };
        /**
         * LoginRequest
         * @description Credentials for ``POST /auth/login``.
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * NewCardPolicyName
         * @description How new cards are chosen each day.
         * @enum {string}
         */
        NewCardPolicyName: "strict_order" | "mastery_unlock" | "pinned_levels";
        /**
         * NewLimits
         * @description Daily new-card limits per item type, counted in cards. ``0`` means unlimited.
         */
        "NewLimits-Input": {
            /**
             * Kana
             * @default 20
             */
            kana: number;
            /**
             * Kanji
             * @default 15
             */
            kanji: number;
            /**
             * Vocab
             * @default 20
             */
            vocab: number;
        };
        /**
         * NewLimits
         * @description Daily new-card limits per item type, counted in cards. ``0`` means unlimited.
         */
        "NewLimits-Output": {
            /**
             * Kana
             * @default 20
             */
            kana: number;
            /**
             * Kanji
             * @default 15
             */
            kanji: number;
            /**
             * Vocab
             * @default 20
             */
            vocab: number;
        };
        /**
         * NextCard
         * @description Response of ``GET /reviews/next``.
         *
         *     ``card`` is ``None`` when nothing is due and no new card is available; ``next_due_at``
         *     then says when the next scheduled card (for example a learning step) comes due.
         */
        NextCard: {
            card: components["schemas"]["CardView"] | null;
            counts: components["schemas"]["ReviewCounts"];
            /** Next Due At */
            next_due_at: string | null;
        };
        /**
         * RefreshRequest
         * @description Body of ``POST /auth/refresh``.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ReviewCounts
         * @description What is left to do right now.
         */
        ReviewCounts: {
            due: components["schemas"]["TypeCounts"];
            new_remaining: components["schemas"]["TypeCounts"];
        };
        /**
         * ReviewSettings
         * @description Every review setting. ``PUT /settings`` replaces the whole document.
         */
        "ReviewSettings-Input": {
            /** Active Levels */
            active_levels?: ("N1" | "N2" | "N3" | "N4" | "N5")[];
            /**
             * Mastery Threshold
             * @default 0.8
             */
            mastery_threshold: number;
            /** @default strict_order */
            new_card_policy: components["schemas"]["NewCardPolicyName"];
            new_limits?: components["schemas"]["NewLimits-Input"];
            /**
             * Rollover Hour
             * @default 4
             */
            rollover_hour: number;
            /**
             * Target Retention
             * @default 0.9
             */
            target_retention: number;
        };
        /**
         * ReviewSettings
         * @description Every review setting. ``PUT /settings`` replaces the whole document.
         */
        "ReviewSettings-Output": {
            /** Active Levels */
            active_levels: ("N1" | "N2" | "N3" | "N4" | "N5")[];
            /**
             * Mastery Threshold
             * @default 0.8
             */
            mastery_threshold: number;
            /** @default strict_order */
            new_card_policy: components["schemas"]["NewCardPolicyName"];
            new_limits: components["schemas"]["NewLimits-Output"];
            /**
             * Rollover Hour
             * @default 4
             */
            rollover_hour: number;
            /**
             * Target Retention
             * @default 0.9
             */
            target_retention: number;
        };
        /**
         * RubySegment
         * @description A run of text, optionally with a furigana reading.
         */
        RubySegment: {
            /** Base */
            base: string;
            /**
             * Highlighted
             * @default false
             */
            highlighted: boolean;
            /** Reading */
            reading?: string | null;
        };
        /**
         * SchedState
         * @description Scheduling state. ``NEW`` means the card has no ``card_state`` row yet.
         * @enum {integer}
         */
        SchedState: 0 | 1 | 2 | 3;
        /**
         * Sentence
         * @description A Japanese example sentence with its English translation.
         */
        Sentence: {
            /** English */
            english: string;
            /** Segments */
            segments: components["schemas"]["RubySegment"][];
        };
        /**
         * StatsSummary
         * @description Response of ``GET /stats/summary``.
         */
        StatsSummary: {
            /** By Level */
            by_level: components["schemas"]["LevelProgress"][];
            /** By Type */
            by_type: {
                [key: string]: components["schemas"]["TypeProgress"];
            };
            /** Daily Reviews */
            daily_reviews: components["schemas"]["DayCount"][];
            introduced_today: components["schemas"]["TypeCounts"];
            /** Retention 30D */
            retention_30d: number | null;
            /** Reviewed Today */
            reviewed_today: number;
        };
        /**
         * TokenResponse
         * @description An access and refresh token.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
        };
        /**
         * TypeCounts
         * @description A count per item type.
         */
        TypeCounts: {
            /**
             * Kana
             * @default 0
             */
            kana: number;
            /**
             * Kanji
             * @default 0
             */
            kanji: number;
            /**
             * Vocab
             * @default 0
             */
            vocab: number;
        };
        /**
         * TypeProgress
         * @description Cards of one item type by scheduling state.
         */
        TypeProgress: {
            /** Learning */
            learning: number;
            /** Relearning */
            relearning: number;
            /** Review */
            review: number;
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Vocab
         * @description A vocabulary item imported from the JLPT deck.
         */
        Vocab: {
            /**
             * Additional Definitions
             * @default
             */
            additional_definitions: string;
            /** Expression */
            expression: string;
            /** Id */
            id: string;
            level: components["schemas"]["JlptLevel"];
            /** Meaning */
            meaning: string;
            /**
             * Part Of Speech
             * @default []
             */
            part_of_speech: string[];
            /** Reading */
            reading: string;
            /** Reading Segments */
            reading_segments: components["schemas"]["RubySegment"][];
            sentence?: components["schemas"]["Sentence"] | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /**
         * WsAuthMessage
         * @description First message a WebSocket client must send.
         */
        WsAuthMessage: {
            /** Token */
            token: string;
            /**
             * Type
             * @constant
             */
            type: "auth";
        };
        /**
         * WsEvent
         * @description One build event.
         */
        WsEvent: {
            event: components["schemas"]["BuildEventModel"];
            /**
             * Type
             * @default event
             * @constant
             */
            type: "event";
        };
        /**
         * WsReady
         * @description Sent once after a successful WebSocket authentication.
         */
        WsReady: {
            /**
             * Type
             * @default ready
             * @constant
             */
            type: "ready";
        };
        /**
         * WsSnapshot
         * @description The latest known build, sent right after ``ready``.
         */
        WsSnapshot: {
            task: components["schemas"]["BuildStatusResponse"];
            /**
             * Type
             * @default snapshot
             * @constant
             */
            type: "snapshot";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfigCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigCheckResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLatestContentBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The item or task does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startContentBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state (for example a stale card). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getContentBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildStatusResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The item or task does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many failed logins; wait for the number of seconds in Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getContentSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSummaryResponse"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is in error; the body still lists every component. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    answerReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCounts"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The item or task does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state (for example a stale card). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Content has not been built, or content.db cannot be used. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getNextReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextCard"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content has not been built, or content.db cannot be used. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettings-Output"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSettings-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettings-Output"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStatsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            /** @description Missing, invalid or expired access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content has not been built, or content.db cannot be used. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
